sudo: required

services:
  - docker

before_install:
  - docker build -t ajay/docker-react -f Dockerfile.dev .
  
scripts:
  - docker run -e CI=true ajay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker-whatever"
  env: "ReactDockerWhatever-env"
  bucket_name: "elasticbeanstalk-us-east-2-478198489334"
  bucket_path: "react-docker-whatever"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY