sudo: required

services:
  - docker

before_install:
  - docker build -t ajay/docker-react -f Dockerfile.dev .
  
scripts:
  - docker run -e CI=true ajay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-478198489334"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_KEY"